# Generated during PKGBUILD from git:batocera.linux:a0d3684e9716234df64b9b549b19923745cbbffe, git:batocera-emulationstation: b13128bb0719a9f58e6e1af2f88242077fdc5ed9
# sources:
# /etc/batocera-emulationstation/supported_systems.json
# /etc/batocera-emulationstation/conf.d/properties/00-supported_configs.json
# /etc/batocera-emulationstation/conf.d/properties/01-property-overrides.conf

