# Generated during PKGBUILD from git:batocera.linux:a0d3684e9716234df64b9b549b19923745cbbffe, git:batocera-emulationstation: b13128bb0719a9f58e6e1af2f88242077fdc5ed9
# sources:
# /opt/batocera-emulationstation/conf.d/batocera.conf
# /opt/batocera-emulationstation/conf.d/configgen-defaults.yml
# /opt/batocera-emulationstation/conf.d/configgen-defaults-x86_64.yml
# /etc/batocera-emulationstation/supported_systems.json
# /etc/batocera-emulationstation/conf.d/properties/00-supported_configs.json
# /etc/batocera-emulationstation/conf.d/properties/01-property-overrides.conf

default.bezel=consoles
default.forceNoBezel=false
default.gamemode_enable=false
default.hud_support=true
default.ratio=auto
default.rewind=false
default.shaderset=sharp-bilinear-simple
default.smooth=true
default.video_frame_delay_auto=true
default.video_threaded=false
default.videomode=default
gba.core=mgba
gba.emulator=libretro
ports.bezel=none
ports.emulator=sh
ps2.emulator=pcsx2
ps2.fullboot=true
windows.emulator=wine
windows.hud_support=false
windows_installers.emulator=wine
windows_installers.hud_support=false
xbox.emulator=xemu
xbox360.emulator=xenia-canary
xbox360.hud_support=false
