# Generated during PKGBUILD from git:batocera.linux:a0d3684e9716234df64b9b549b19923745cbbffe, git:batocera-emulationstation: b13128bb0719a9f58e6e1af2f88242077fdc5ed9
# sources:
# /opt/batocera-emulationstation/conf.d/batocera.conf
# /opt/batocera-emulationstation/conf.d/configgen-defaults.yml
# /opt/batocera-emulationstation/conf.d/configgen-defaults-x86_64.yml
# /etc/batocera-emulationstation/supported_systems.json
# /etc/batocera-emulationstation/conf.d/properties/00-supported_configs.json
# /etc/batocera-emulationstation/conf.d/properties/01-property-overrides.conf

audio.bgmusic=1
audio.device=auto
audio.volume=90
controllers.bluetooth.enabled=1
controllers.db9.args=map=1
controllers.db9.enabled=0
controllers.gamecon.args=map=1
controllers.gamecon.enabled=0
controllers.gpio.args=map=1,2
controllers.gpio.enabled=0
controllers.ps3.driver=bluez
controllers.ps3.enabled=1
controllers.xarcade.enabled=1
system.hostname=BATOCERA
wifi.enabled=0
