Object.assign(globalThis, require('test-helpers.mjs'));

const assert = require('node:assert/strict');

enableLogfile();

const TEST_RESOURCE_ROOT = ROOT_PATH + "/test/resource/fs_root";
const CONFIG_ROOT = TEST_RESOURCE_ROOT + "/configs";
const DROPIN_DIR = TEST_RESOURCE_ROOT + "/configs/dropins";
const BTC_BIN_DIR = TEST_RESOURCE_ROOT + "/btcDir/bin";
process.env.BTC_BIN_DIR = BTC_BIN_DIR;

const btc = require('btc-config');
const importer = require('config.libs/config-import.js');


class ImportTests {
  testGenerateConfig(){
    let options = {
      '-v': true,
      '--comment': 'Generated by test'
    }
    importer.generateGlobalConfig(options, CONFIG_ROOT, BTC_BIN_DIR, DROPIN_DIR);
    
    //TODO: finish test
    //IDEA: use git status --porcelain TEST_RESOURCE_ROOT)
    //there should be no changes
    //if there are, some change to output/parsing has changed output but was not yet verified
    
  }
}

runTestClass(ImportTests);