name: Create config branch
on: workflow_dispatch

jobs:
  build-config:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: configure git
        run: | 
          git config user.name "Github Bot"
          git config user.email "<>"

      - name: run generator
        run: |
          sudo ln -s /usr/local/bin/node /usr/bin/node
          chmod +x .github/workflows/scripts/generate-config.sh
          .github/workflows/scripts/generate-config.sh

      - name: push config
        run: echo "separate git push from generate-config.sh (take it out there)"
