name: Create config branch
on: workflow_dispatch

jobs:
  build-config:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: configure git
        run: | 
          git config user.name "Github Bot"
          git config user.email "<>"

      - name: run generator
        run: scripts/generate-config.sh --push ./configs