name: Clear old workflows
on: workflow_dispatch

jobs:
  clean-history:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
     -
      name: Delete old workflows
      uses: GB609/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        
        # Days-worth of runs to keep for each workflow
        retain_days: 2
        
        # Minimum runs to keep for each workflow
        keep_minimum_runs: 2
        minimum_ignore_deleted_branches: true

        branch_specific_minimum_runs: true
        workflow_specific_minimum_runs: true
        
        # Name or filename of the workflow (if not set, all workflows are targeted)
        #delete_workflow_pattern: tests.yml, clear_history.yml, update_pages.yml, build_config_branch.yml, pages-build-deployment

        # Remove runs based on conclusion: action_required, cancelled, failure, skipped, success
        #delete_run_by_conclusion_pattern: success, skipped

        # Logs simulated changes, no deletions are performed
        #dry_run: true

        # If the workflow was triggered by a branch, the branch must be deleted before the workflow run is deleted as well.
        #check_branch_existence: true

        #branch_filter: '["main"]'

        # If the run is linked to a pull request, the deletion is skipped.
        check_pullrequest_exist: true
